version: '3.2'
services:
  app:
    container_name: vdr_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env/development/db
      - .env/development/app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
  webpack_dev_server:
    container_name: vdr_webpack-dev-server
    build: .
    command: ./bin/webpack-dev-server
    env_file:
      - .env/development/db
      - .env/development/app
    volumes:
      - .:/app
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  db:
    container_name: vdr_db
    image: postgres
    env_file:
      - .env/development/db
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - "5432:5432"